// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idcwxcvtppiruiwbjrjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkY3d4Y3Z0cHBpcnVpd2JqcmpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMTA4MjYsImV4cCI6MjA1ODg4NjgyNn0.3tO5JFXdXodvgzIA7gE9Bp11-7cz30JBHwZPj8YXN1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);